/**
 * Hosts IRIS's Electron-owned capability bridge on a loopback-only HTTP server in both
 * development and packaged builds. Requests must pass loopback Host validation, an exact
 * renderer Origin allowlist, and the per-launch secret generated by Electron.
 */

import { timingSafeEqual } from 'node:crypto'
import http, { type IncomingMessage, type ServerResponse } from 'node:http'
import path from 'node:path'
import { handleBridgeRequest } from './desktopBridge/routes/router.js'
import {
  closeEncryptedDatabase,
  initializeEncryptedDatabase,
  purgeExpiredEncryptedState,
} from './desktopBridge/storage/encryptedDatabase.js'
import { removeLegacyPlaintextStorage } from './desktopBridge/storage/legacyCleanup.js'
import { closeManagedDevEnvironment } from './desktopBridge/services/launcherService.js'
import {
  configureDuckDuckGoBrowserProvider,
  type DuckDuckGoBrowserSearch,
  type DuckDuckGoSearchMode,
} from './desktopBridge/services/duckDuckGoBrowserProvider.js'
import {
  DEFAULT_BRIDGE_PERMISSIONS,
  normalizeBridgePermissions,
  type BridgePermissionState,
  type BridgeSecurityContext,
} from './desktopBridge/shared/bridgeAuthorization.js'
import { hostnameFromHeader, isLoopbackHost } from './desktopBridge/services/bridgeServiceRuntime.js'
import {
  closeImageGenerationRuntime,
  configureImageGenerationRuntime,
} from './desktopBridge/services/imageGenerationService.js'

const TOKEN_HEADER = 'x-iris-bridge-token'
const TOKEN_QUERY = '__token' // EventSource cannot attach custom request headers.
const DEFAULT_ALLOWED_ORIGINS: readonly string[] = Object.freeze(['null'])
const AUDIO_REQUEST_HEADERS = [
  'x-iris-audio-provider',
  'x-iris-audio-model',
  'x-iris-audio-key',
  'x-iris-audio-local-fallback',
] as const
const ALLOWED_PREFLIGHT_HEADERS = new Set(['content-type', TOKEN_HEADER, ...AUDIO_REQUEST_HEADERS])
const CORS_ALLOWED_HEADERS = ['Content-Type', TOKEN_HEADER, ...AUDIO_REQUEST_HEADERS].join(', ')

interface BridgeServerOptions {
  baseDir?: string
  host?: string
  port?: number
  token?: string
  allowedOrigins?: readonly string[]
  initialPermissions?: Partial<BridgePermissionState>
  databasePath?: string
  masterKey?: Buffer
  duckDuckGoBrowserSearch?: DuckDuckGoBrowserSearch
  duckDuckGoSearchMode?: DuckDuckGoSearchMode
}

interface BridgeErrorLike {
  statusCode?: number
  message?: string
  code?: string
}

// Sends end JSON using the bridge's stable HTTP response shape.
function endJson(res: ServerResponse, statusCode: number, payload: Record<string, unknown>): void {
  res.statusCode = statusCode
  res.setHeader('Content-Type', 'application/json; charset=utf-8')
  res.setHeader('X-Content-Type-Options', 'nosniff')
  res.end(JSON.stringify(payload ?? {}))
}

// Normalizes token equals to a safe fallback when provider data is missing or malformed.
function safeTokenEquals(actual: unknown, expected: string): boolean {
  const left = Buffer.from(String(actual || ''), 'utf8')
  const right = Buffer.from(String(expected || ''), 'utf8')
  return left.length === right.length && timingSafeEqual(left, right)
}

// Determines whether the token matches for the local bridge runtime.
function tokenMatches(req: IncomingMessage, expected: string): boolean {
  const headerToken = req.headers?.[TOKEN_HEADER]
  if (headerToken && safeTokenEquals(headerToken, expected)) return true
  try {
    const url = new URL(req.url ?? '/', 'http://127.0.0.1')
    return safeTokenEquals(url.searchParams.get(TOKEN_QUERY), expected)
  } catch {
    return false
  }
}

// Determines whether the request host is loopback for the local bridge runtime.
function requestHostIsLoopback(req: IncomingMessage): boolean {
  const hostname = hostnameFromHeader(req.headers?.host || '')
  return Boolean(hostname && isLoopbackHost(hostname))
}

// Determines whether the origin is allowed for the local bridge runtime.
function originIsAllowed(req: IncomingMessage, allowedOrigins: ReadonlySet<string>): boolean {
  const origin = req.headers?.origin
  if (!origin) return true
  return allowedOrigins.has(String(origin))
}

// Determines whether the requested headers are allowed for the local bridge runtime.
function requestedHeadersAreAllowed(req: IncomingMessage): boolean {
  const requested = String(req.headers?.['access-control-request-headers'] || '')
    .split(',')
    .map((value) => value.trim().toLowerCase())
    .filter(Boolean)
  return requested.every((name) => ALLOWED_PREFLIGHT_HEADERS.has(name))
}

// Applies CORS to the current state using the rules owned by the local bridge runtime.
function applyCors(req: IncomingMessage, res: ServerResponse, allowedOrigins: ReadonlySet<string>): void {
  const origin = req.headers?.origin
  if (!origin || !allowedOrigins.has(String(origin))) return
  res.setHeader('Access-Control-Allow-Origin', String(origin))
  res.setHeader('Vary', 'Origin')
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', CORS_ALLOWED_HEADERS)
  res.setHeader('Access-Control-Max-Age', '600')
}

/**
 * Starts the packaged loopback bridge after checking that its authentication material is
 * strong enough for a production boundary. `allowedOrigins` normally remains `null`, the
 * opaque origin sent by a file:// renderer; tests or future custom protocols may opt into
 * additional exact origins explicitly.
 */
export async function startLocalBridgeServer({
  baseDir = process.cwd(),
  host = '127.0.0.1',
  port = 0,
  token = '',
  allowedOrigins = DEFAULT_ALLOWED_ORIGINS,
  initialPermissions = DEFAULT_BRIDGE_PERMISSIONS,
  databasePath = '',
  masterKey,
  duckDuckGoBrowserSearch,
  duckDuckGoSearchMode,
}: BridgeServerOptions = {}) {
  if (typeof token !== 'string' || token.length < 32) {
    throw new Error('Packaged bridge startup requires a per-launch token of at least 32 characters.')
  }

  if (!databasePath || !Buffer.isBuffer(masterKey) || masterKey.length !== 32) {
    throw new Error('Encrypted storage configuration is required before bridge startup.')
  }

  configureImageGenerationRuntime({ dataDir: path.dirname(databasePath) })

  try {
    await initializeEncryptedDatabase({ databasePath, masterKey })
    await removeLegacyPlaintextStorage(databasePath)
    await purgeExpiredEncryptedState()
  } catch (error) {
    await closeEncryptedDatabase().catch(() => undefined)
    throw error
  }

  const releaseDuckDuckGoBrowserProvider = configureDuckDuckGoBrowserProvider({
    search: duckDuckGoBrowserSearch,
    mode: duckDuckGoSearchMode,
  })
  const originAllowlist = new Set(allowedOrigins.map((value) => String(value)))
  const securityContext: BridgeSecurityContext = {
    permissions: normalizeBridgePermissions(initialPermissions),
  }

  const server = http.createServer(async (req, res) => {
    if (!requestHostIsLoopback(req)) {
      endJson(res, 403, { error: 'Forbidden: bridge Host must be loopback.' })
      return
    }
    if (!originIsAllowed(req, originAllowlist)) {
      endJson(res, 403, { error: 'Forbidden: bridge Origin is not allowed.' })
      return
    }

    if (req.method === 'OPTIONS') {
      if (!requestedHeadersAreAllowed(req)) {
        endJson(res, 403, {
          error: 'Forbidden: preflight requested unsupported headers.',
        })
        return
      }
      applyCors(req, res, originAllowlist)
      res.statusCode = 204
      res.end()
      return
    }

    if (!req.url || !req.url.startsWith('/api/local/')) {
      endJson(res, 404, { error: 'Not found' })
      return
    }
    if (!tokenMatches(req, token)) {
      endJson(res, 403, {
        error: 'Forbidden: missing or invalid bridge token.',
      })
      return
    }

    applyCors(req, res, originAllowlist)
    try {
      const handled = await handleBridgeRequest(req, res, baseDir, securityContext)
      if (!handled && !res.writableEnded) {
        endJson(res, 404, { error: `Unknown local bridge route: ${req.url}` })
      }
    } catch (error: unknown) {
      if (res.writableEnded) return
      const candidate = error as BridgeErrorLike
      const statusCode = Number.isInteger(candidate.statusCode) ? Number(candidate.statusCode) : 500
      endJson(res, statusCode, {
        error: candidate.message || 'Unexpected local bridge error',
        ...(candidate.code ? { code: candidate.code } : {}),
      })
    }
  })

  const bindHost = /^(127\.|::1$|localhost$)/.test(host) ? host : '127.0.0.1'
  try {
    await new Promise<void>((resolve, reject) => {
      server.once('error', reject)
      server.listen(port, bindHost, resolve)
    })
  } catch (error) {
    releaseDuckDuckGoBrowserProvider()
    await closeEncryptedDatabase().catch(() => undefined)
    throw error
  }

  const address = server.address()
  const boundPort = address && typeof address === 'object' ? address.port : port
  return {
    port: boundPort,
    host: bindHost,
    token,
    getPermissions: (): BridgePermissionState => ({
      ...securityContext.permissions,
    }),
    // Updates permissions while preserving the invariants owned by the local bridge runtime.
    updatePermissions: (permissions: Partial<BridgePermissionState>): BridgePermissionState => {
      securityContext.permissions = normalizeBridgePermissions(permissions, securityContext.permissions)
      return { ...securityContext.permissions }
    },
    close: () =>
      new Promise<void>((resolve) => {
        server.close(() => {
          releaseDuckDuckGoBrowserProvider()
          void closeManagedDevEnvironment()
            .catch(() => undefined)
            .then(() => closeImageGenerationRuntime())
            .then(() => closeEncryptedDatabase())
            .finally(resolve)
        })
      }),
  }
}
